"""Update users lenght table

Revision ID: ca2e1604f9d6
Revises: 45fde44bc98b
Create Date: 2025-04-15 15:27:28.179710

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca2e1604f9d6"
down_revision: Union[str, None] = "45fde44bc98b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assignments",
        "title",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=127),
        existing_nullable=False,
    )
    op.alter_column(
        "groups",
        "title",
        existing_type=sa.VARCHAR(length=63),
        type_=sa.String(length=127),
        existing_nullable=False,
    )
    op.alter_column(
        "groups",
        "description",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.add_column(
        "tasks", sa.Column("title", sa.String(length=127), nullable=False)
    )
    op.add_column(
        "tasks",
        sa.Column("description", sa.String(length=255), nullable=False),
    )
    op.drop_column("tasks", "text")
    op.drop_column("tasks", "name")
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=127),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=1023),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.String(length=1023),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=127),
        type_=sa.VARCHAR(length=320),
        existing_nullable=False,
    )
    op.add_column(
        "tasks",
        sa.Column(
            "name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "tasks",
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("tasks", "description")
    op.drop_column("tasks", "title")
    op.alter_column(
        "groups",
        "description",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "groups",
        "title",
        existing_type=sa.String(length=127),
        type_=sa.VARCHAR(length=63),
        existing_nullable=False,
    )
    op.alter_column(
        "assignments",
        "title",
        existing_type=sa.String(length=127),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
