"""Create user_profles table

Revision ID: 3ab6e1354f19
Revises: 5fb32412f74a
Create Date: 2025-03-25 18:05:13.372443

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ab6e1354f19"
down_revision: Union[str, None] = "5fb32412f74a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=31), nullable=False),
        sa.Column("surname", sa.String(length=31), nullable=False),
        sa.Column("patronymic", sa.String(length=63), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_profiles_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_profiles")),
    )
    op.create_index(
        op.f("ix_user_profiles_name"), "user_profiles", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_user_profiles_patronymic"),
        "user_profiles",
        ["patronymic"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_profiles_surname"),
        "user_profiles",
        ["surname"],
        unique=False,
    )
    op.drop_constraint(
        "fk_groups_admin_id_users", "groups", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_groups_admin_id_user_profiles"),
        "groups",
        "user_profiles",
        ["admin_id"],
        ["user_id"],
    )
    op.drop_constraint("fk_tasks_admin_id_users", "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_tasks_admin_id_user_profiles"),
        "tasks",
        "user_profiles",
        ["admin_id"],
        ["user_id"],
    )
    op.drop_constraint(
        "fk_user_group_association_table_user_id_users",
        "user_group_association_table",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_group_association_table_user_id_user_profiles"),
        "user_group_association_table",
        "user_profiles",
        ["user_id"],
        ["user_id"],
    )
    op.drop_column("users", "name")
    op.drop_column("users", "surname")
    op.drop_column("users", "patronymic")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "patronymic",
            sa.VARCHAR(length=63),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "surname",
            sa.VARCHAR(length=31),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "name", sa.VARCHAR(length=31), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_user_group_association_table_user_id_user_profiles"),
        "user_group_association_table",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_user_group_association_table_user_id_users",
        "user_group_association_table",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_tasks_admin_id_user_profiles"), "tasks", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_tasks_admin_id_users", "tasks", "users", ["admin_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_groups_admin_id_user_profiles"), "groups", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_groups_admin_id_users", "groups", "users", ["admin_id"], ["id"]
    )
    op.drop_index(op.f("ix_user_profiles_surname"), table_name="user_profiles")
    op.drop_index(
        op.f("ix_user_profiles_patronymic"), table_name="user_profiles"
    )
    op.drop_index(op.f("ix_user_profiles_name"), table_name="user_profiles")
    op.drop_table("user_profiles")
    # ### end Alembic commands ###
