"""Change access_tokens table

Revision ID: ff4557512b96
Revises: ca2e1604f9d6
Create Date: 2025-04-16 23:23:32.899513

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff4557512b96"
down_revision: Union[str, None] = "ca2e1604f9d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "access_tokens",
        "token",
        existing_type=sa.VARCHAR(length=43),
        type_=sa.String(length=511),
        existing_nullable=False,
    )
    op.drop_index("ix_access_tokens_created_at", table_name="access_tokens")
    op.drop_constraint(
        "fk_access_tokens_user_id_users", "access_tokens", type_="foreignkey"
    )
    op.add_column(
        "access_tokens",
        sa.Column(
            "created_at",
            sa.String(length=15),
            nullable=False,
            server_default=sa.text("str(datetime.now(utc))"),
        ),
    )
    op.create_foreign_key(
        op.f("fk_access_tokens_user_id_users"),
        "access_tokens",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_primary_key("pk_access_tokens", "access_tokens", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_access_tokens_user_id_users"),
        "access_tokens",
        type_="foreignkey",
    )
    op.drop_constraint("pk_access_tokens", "access_tokens", type_="primary")
    op.create_foreign_key(
        "fk_access_tokens_user_id_users",
        "access_tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "ix_access_tokens_created_at",
        "access_tokens",
        ["created_at"],
        unique=False,
    )
    op.alter_column(
        "access_tokens",
        "token",
        existing_type=sa.String(length=511),
        type_=sa.VARCHAR(length=43),
        existing_nullable=False,
    )
    op.drop_column("access_tokens", "created_at")
