"""Create Assignment

Revision ID: 6819d3364a53
Revises: 3ab6e1354f19
Create Date: 2025-04-01 16:39:29.647968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6819d3364a53"
down_revision: Union[str, None] = "3ab6e1354f19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assignments",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("is_contest", sa.Boolean(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["user_profiles.user_id"],
            name=op.f("fk_assignments_admin_id_user_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_assignments_group_id_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignments")),
    )
    op.create_index(op.f("ix_assignments_id"), "assignments", ["id"], unique=False)
    op.add_column("tasks", sa.Column("assignment_id", sa.Integer(), nullable=False))
    op.add_column("tasks", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_constraint("fk_tasks_admin_id_user_profiles", "tasks", type_="foreignkey")
    op.drop_constraint("fk_tasks_group_id_groups", "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_tasks_assignment_id_assignments"),
        "tasks",
        "assignments",
        ["assignment_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_tasks_user_id_user_profiles"),
        "tasks",
        "user_profiles",
        ["user_id"],
        ["user_id"],
    )
    op.drop_column("tasks", "admin_id")
    op.drop_column("tasks", "group_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "tasks",
        sa.Column("admin_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_tasks_user_id_user_profiles"), "tasks", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_tasks_assignment_id_assignments"), "tasks", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_tasks_group_id_groups", "tasks", "groups", ["group_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_tasks_admin_id_user_profiles",
        "tasks",
        "user_profiles",
        ["admin_id"],
        ["user_id"],
    )
    op.drop_column("tasks", "user_id")
    op.drop_column("tasks", "assignment_id")
    op.drop_index(op.f("ix_assignments_id"), table_name="assignments")
    op.drop_table("assignments")
    # ### end Alembic commands ###
