"""Add model for safe link to groups

Revision ID: 95160571b5fb
Revises: f6de201dd350
Create Date: 2025-05-23 11:34:22.264291

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95160571b5fb"
down_revision: Union[str, None] = "f6de201dd350"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_invites",
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_group_invites_group_id_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_invites")),
    )
    op.create_index(
        op.f("ix_group_invites_code"), "group_invites", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_group_invites_id"), "group_invites", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_group_invites_id"), table_name="group_invites")
    op.drop_index(op.f("ix_group_invites_code"), table_name="group_invites")
    op.drop_table("group_invites")
    # ### end Alembic commands ###
