"""Rework group_invites and add space_join_requests

Revision ID: ce79772e24c8
Revises: 0454238a41fe
Create Date: 2025-07-18 19:42:42.703221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ce79772e24c8"
down_revision: Union[str, None] = "0454238a41fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "space_invites",
        sa.Column("space_invite_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("space_id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_usages", sa.Integer(), nullable=True),
        sa.Column("users_usages", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("needs_approval", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["accounts.id"],
            name=op.f("fk_space_invites_creator_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
            name=op.f("fk_space_invites_space_id_spaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_space_invites")),
    )
    op.create_index(op.f("ix_space_invites_id"), "space_invites", ["id"], unique=False)
    op.create_index(
        op.f("ix_space_invites_space_invite_type"),
        "space_invites",
        ["space_invite_type"],
        unique=False,
    )
    op.create_table(
        "space_join_requests",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("space_id", sa.Integer(), nullable=False),
        sa.Column("space_invite_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
            name=op.f("fk_space_join_requests_space_id_spaces"),
        ),
        sa.ForeignKeyConstraint(
            ["space_invite_id"],
            ["space_invites.id"],
            name=op.f("fk_space_join_requests_space_invite_id_space_invites"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profiles.user_id"],
            name=op.f("fk_space_join_requests_user_id_user_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_space_join_requests")),
    )
    op.create_index(
        op.f("ix_space_join_requests_id"),
        "space_join_requests",
        ["id"],
        unique=False,
    )
    op.alter_column(
        "group_invites",
        "code",
        existing_type=sa.VARCHAR(length=8),
        type_=sa.String(length=16),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_group_invites_id"), table_name="group_invites")
    op.drop_constraint(
        op.f("fk_group_invites_space_id_spaces"),
        "group_invites",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_group_invites_id_space_invites"),
        "group_invites",
        "space_invites",
        ["id"],
        ["id"],
    )
    op.drop_column("group_invites", "space_id")
    op.drop_column("group_invites", "is_active")
    op.drop_column("group_invites", "expires_at")
    op.drop_constraint(
        op.f("fk_modules_creator_id_user_profiles"),
        "modules",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_modules_creator_id_accounts"),
        "modules",
        "accounts",
        ["creator_id"],
        ["id"],
    )
    op.add_column("solutions", sa.Column("creator_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f("fk_solutions_account_id_accounts"),
        "solutions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_solutions_creator_id_accounts"),
        "solutions",
        "accounts",
        ["creator_id"],
        ["id"],
    )
    op.drop_column("solutions", "account_id")
    op.drop_constraint(
        op.f("fk_tasks_creator_id_user_profiles"), "tasks", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_tasks_creator_id_accounts"),
        "tasks",
        "accounts",
        ["creator_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_tasks_creator_id_accounts"), "tasks", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_tasks_creator_id_user_profiles"),
        "tasks",
        "user_profiles",
        ["creator_id"],
        ["user_id"],
    )
    op.add_column(
        "solutions",
        sa.Column("account_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_solutions_creator_id_accounts"),
        "solutions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_solutions_account_id_accounts"),
        "solutions",
        "accounts",
        ["account_id"],
        ["id"],
    )
    op.drop_column("solutions", "creator_id")
    op.drop_constraint(
        op.f("fk_modules_creator_id_accounts"), "modules", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_modules_creator_id_user_profiles"),
        "modules",
        "user_profiles",
        ["creator_id"],
        ["user_id"],
    )
    op.add_column(
        "group_invites",
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "group_invites",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "group_invites",
        sa.Column("space_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_group_invites_id_space_invites"),
        "group_invites",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_group_invites_space_id_spaces"),
        "group_invites",
        "spaces",
        ["space_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(op.f("ix_group_invites_id"), "group_invites", ["id"], unique=False)
    op.alter_column(
        "group_invites",
        "code",
        existing_type=sa.String(length=16),
        type_=sa.VARCHAR(length=8),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_space_join_requests_id"), table_name="space_join_requests")
    op.drop_table("space_join_requests")
    op.drop_index(
        op.f("ix_space_invites_space_invite_type"), table_name="space_invites"
    )
    op.drop_index(op.f("ix_space_invites_id"), table_name="space_invites")
    op.drop_table("space_invites")
    # ### end Alembic commands ###
