"""Update task

Revision ID: 8f681bf247f7
Revises: 257f2b7c2f21
Create Date: 2025-04-27 12:07:22.404695

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f681bf247f7"
down_revision: Union[str, None] = "257f2b7c2f21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignments",
        sa.Column("tasks_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "tasks",
        sa.Column("max_attempts", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "user_replys",
        sa.Column("user_attempts", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_replys", "user_attempts")
    op.drop_column("tasks", "max_attempts")
    op.drop_column("assignments", "tasks_count")
    # ### end Alembic commands ###
