"""change invites table

Revision ID: 0033c3622eb4
Revises: a0c9b849ca80
Create Date: 2025-07-04 09:09:51.163073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0033c3622eb4"
down_revision: Union[str, None] = "a0c9b849ca80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group_invites", sa.Column("space_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        op.f("fk_group_invites_group_id_groups"),
        "group_invites",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_group_invites_space_id_spaces"),
        "group_invites",
        "spaces",
        ["space_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("group_invites", "group_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group_invites",
        sa.Column(
            "group_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_group_invites_space_id_spaces"),
        "group_invites",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_group_invites_group_id_groups"),
        "group_invites",
        "groups",
        ["group_id"],
        ["id"],
    )
    op.drop_column("group_invites", "space_id")
    # ### end Alembic commands ###
