"""Create user_replys table

Revision ID: 257f2b7c2f21
Revises: 02e3e53fcf14
Create Date: 2025-04-23 12:26:54.619948

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "257f2b7c2f21"
down_revision: Union[str, None] = "02e3e53fcf14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_replys",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("user_answer", sa.String(length=255), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_user_replys_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_user_replys_task_id_tasks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_replys")),
    )
    op.create_index(
        op.f("ix_user_replys_id"), "user_replys", ["id"], unique=False
    )
    op.drop_constraint(
        "fk_tasks_account_id_accounts", "tasks", type_="foreignkey"
    )
    op.drop_column("tasks", "account_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "account_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "fk_tasks_account_id_accounts",
        "tasks",
        "accounts",
        ["account_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_user_replys_id"), table_name="user_replys")
    op.drop_table("user_replys")
    # ### end Alembic commands ###
