"""Chat fix

Revision ID: 0a190ed674ed
Revises: 8a75699b468b
Create Date: 2025-08-03 00:18:49.298233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a190ed674ed"
down_revision: Union[str, None] = "8a75699b468b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["accounts.id"],
            name=op.f("fk_chats_creator_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_chats_group_id_groups")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chats")),
    )
    op.create_index(op.f("ix_chats_id"), "chats", ["id"], unique=False)
    op.create_table(
        "chat_account_associations",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_chat_account_associations_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
            name=op.f("fk_chat_account_associations_chat_id_chats"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_account_associations")),
    )
    op.create_index(
        op.f("ix_chat_account_associations_id"),
        "chat_account_associations",
        ["id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_chat_account_association_id"),
        table_name="chat_account_association",
    )
    op.drop_table("chat_account_association")
    op.drop_constraint(op.f("fk_messages_chat_id_chat"), "messages", type_="foreignkey")
    op.drop_table("chat")
    op.add_column("messages", sa.Column("is_edited", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)

    op.create_foreign_key(
        op.f("fk_messages_chat_id_chats"),
        "messages",
        "chats",
        ["chat_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_messages_chat_id_chats"), "messages", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_messages_chat_id_chat"),
        "messages",
        "chat",
        ["chat_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_column("messages", "is_edited")
    op.create_table(
        "chat",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('chat_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("creator_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["accounts.id"], name="fk_chat_creator_id_accounts"
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name="fk_chat_group_id_groups"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_chat"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "chat_account_association",
        sa.Column("chat_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_chat_account_association_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.id"],
            name=op.f("fk_chat_account_association_chat_id_chat"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_account_association")),
    )
    op.create_index(
        op.f("ix_chat_account_association_id"),
        "chat_account_association",
        ["id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_chat_account_associations_id"),
        table_name="chat_account_associations",
    )
    op.drop_table("chat_account_associations")
    op.drop_index(op.f("ix_chats_id"), table_name="chats")
    op.drop_table("chats")
    # ### end Alembic commands ###
