"""Add deadlines to assignments

Revision ID: f6de201dd350
Revises: b76850d5ce14
Create Date: 2025-05-17 21:00:07.040444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6de201dd350"
down_revision: Union[str, None] = "b76850d5ce14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignments",
        sa.Column(
            "start_datetime",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.add_column(
        "assignments",
        sa.Column(
            "end_datetime",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.add_column(
        "assignments",
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignments", "is_active")
    op.drop_column("assignments", "end_datetime")
    op.drop_column("assignments", "start_datetime")
    # ### end Alembic commands ###
