"""Remove some properties

Revision ID: 42f061eab254
Revises: b1ade672322c
Create Date: 2025-07-06 18:07:08.743270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42f061eab254"
down_revision: Union[str, None] = "b1ade672322c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("courses")
    op.add_column("spaces", sa.Column("creator_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_spaces_creator_id_user_profiles"),
        "spaces",
        "user_profiles",
        ["creator_id"],
        ["user_id"],
    )
    op.add_column("tasks", sa.Column("creator_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_tasks_creator_id_user_profiles"),
        "tasks",
        "user_profiles",
        ["creator_id"],
        ["user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_tasks_creator_id_user_profiles"), "tasks", type_="foreignkey"
    )
    op.drop_column("tasks", "creator_id")
    op.drop_constraint(
        op.f("fk_spaces_creator_id_user_profiles"),
        "spaces",
        type_="foreignkey",
    )
    op.drop_column("spaces", "creator_id")
    op.create_table(
        "courses",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["spaces.id"], name=op.f("fk_courses_id_spaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
    )
    # ### end Alembic commands ###
