"""Add Multiple choise and feedback

Revision ID: 0e3edf962eee
Revises: 155b9d224935
Create Date: 2025-07-30 15:16:51.003477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e3edf962eee"
down_revision: Union[str, None] = "155b9d224935"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "multiple_choice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("correct_answer", sa.ARRAY(sa.String()), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["tasks.id"],
            name=op.f("fk_multiple_choice_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_multiple_choice")),
    )
    op.create_table(
        "multiple_choice_solutions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_answer", sa.ARRAY(sa.String()), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["solutions.id"],
            name=op.f("fk_multiple_choice_solutions_id_solutions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_multiple_choice_solutions")),
    )
    op.create_table(
        "solution_feedbacks",
        sa.Column("solution_id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(length=1000), nullable=False),
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("is_updated", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["accounts.id"],
            name=op.f("fk_solution_feedbacks_creator_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["solution_id"],
            ["solutions.id"],
            name=op.f("fk_solution_feedbacks_solution_id_solutions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_solution_feedbacks")),
    )
    op.create_index(
        op.f("ix_solution_feedbacks_id"),
        "solution_feedbacks",
        ["id"],
        unique=False,
    )
    op.drop_column("tasks", "manual_grading")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("manual_grading", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_solution_feedbacks_id"), table_name="solution_feedbacks")
    op.drop_table("solution_feedbacks")
    op.drop_table("multiple_choice_solutions")
    op.drop_table("multiple_choice")
    # ### end Alembic commands ###
