"""change nullable fields in users

Revision ID: 3eee872825ac
Revises: d142939da173
Create Date: 2025-07-07 09:34:34.487704

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3eee872825ac"
down_revision: Union[str, None] = "d142939da173"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=127), nullable=True
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=1023), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.VARCHAR(length=1023),
        nullable=False,
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=127), nullable=False
    )
    # ### end Alembic commands ###
