"""Create deadlines

Revision ID: b76850d5ce14
Revises: 8f681bf247f7
Create Date: 2025-05-01 14:47:45.314733

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision: str = "b76850d5ce14"
down_revision: Union[str, None] = "8f681bf247f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "start_datetime",
            sa.DateTime(timezone=True),
            server_default=func.now(),
            nullable=False,
        ),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "end_datetime",
            sa.DateTime(timezone=True),
            server_default=func.now(),
            nullable=False,
        ),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "is_active")
    op.drop_column("tasks", "end_datetime")
    op.drop_column("tasks", "start_datetime")
    # ### end Alembic commands ###
