"""Add task and module progress models

Revision ID: 8a75699b468b
Revises: 0e3edf962eee
Create Date: 2025-07-31 16:29:42.544423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a75699b468b"
down_revision: Union[str, None] = "0e3edf962eee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_module_progresses",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("user_completed_tasks_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_account_module_progresses_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.id"],
            name=op.f("fk_account_module_progresses_module_id_modules"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_module_progresses")),
    )
    op.create_index(
        op.f("ix_account_module_progresses_id"),
        "account_module_progresses",
        ["id"],
        unique=False,
    )
    op.create_table(
        "account_task_progresses",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("user_attempts_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_account_task_progresses_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_account_task_progresses_task_id_tasks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_task_progresses")),
    )
    op.create_index(
        op.f("ix_account_task_progresses_id"),
        "account_task_progresses",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_account_task_progresses_id"),
        table_name="account_task_progresses",
    )
    op.drop_table("account_task_progresses")
    op.drop_index(
        op.f("ix_account_module_progresses_id"),
        table_name="account_module_progresses",
    )
    op.drop_table("account_module_progresses")
    # ### end Alembic commands ###
