"""Add nullable title

Revision ID: b26ae366a88e
Revises: ce79772e24c8
Create Date: 2025-07-22 16:13:38.872439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b26ae366a88e"
down_revision: Union[str, None] = "ce79772e24c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "space_invites",
        "title",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "space_invites",
        "title",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    # ### end Alembic commands ###
