{
 "title": "FastAPI Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(fastapi_app_info{}, app_name)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Main logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker-logs\", container_name=\"backend\", logger=\"app\"} | json | line_format \"{{ printf \\\"%-23s | %-5s | %-10s | %-15s | %-6s | %-20s | %-3s | %-36s | %-9s\\\" .time .level .event .client_ip .method .path .status_code .request_id .process_time }}\""
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{app_name=\"$app_name\", handler!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Total Response",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_response_size_bytes_count{app_name=\"$app_name\", handler!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{app_name=\"$app_name\"} / http_request_duration_seconds_count{app_name=\"$app_name\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Other logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 15, "x": 9, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker-logs\", container_name=\"backend\", logger!=\"app\"} | json | line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_request_duration_seconds_bucket{app_name=\"$app_name\", handler!=\"/metrics\"}[1m])) by(handler, le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}